### PR TITLE
Create Fact “buzz-pollination”

### PR DESCRIPTION
**Pull request by floogulinc**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by floogulinc** [comment]
Preview: https://deploy-preview-7--pollinator-facts.netlify.app/f/buzz-pollination/

**Review by kklamberty — COMMENTED** [review]
This looks good to me. Though, for both this one and the one I just approved, what can we do to follow the copyright of the image at the moment? I think it might be important to include that information here and to do it before merging. What do you think?

**Comment by floogulinc** [comment]
Yeah good idea. I will wait to merge them until the site displays the image
information.

**Review by kklamberty — APPROVED** [review]
We talked about this previously being three facts and maybe being a bit large and "splittable". But, it's a nice looking fact and seems ready to go. We can always decide to split it.

**Pull request merged**
